<?php
$replies = $block->getReplyList();
?>
<div class="block block-reply-list">
    <div class="block-title">
        <strong>
            <?= $block->escapeHtml(__('All Replies')) ?>
        </strong>
    </div>
    <div class="block-content">
        <div class="table-wrapper support-replies">
            <table class="data table my-replies-table" id="my-replies-table">
                <caption class="table-caption"><?= 'Your Replies' ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= 'Ticket ID' ?></th>
                        <th scope="col" class="col id"><?= 'Replied By' ?></th>
                        <th scope="col" class="col comment"><?= 'Comment' ?></th>
                        <th scope="col" class="col actions"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($replies as $reply) : ?>
                    <?php if ($block->getCurrentId() == $reply->getSupportId() && $reply->getVisible() == 'visible') : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Ticket ID')) ?>" class="col id"><?= '# ' . $block->escapeHtml($reply->getSupportId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Admin ID')) ?>" class="col id">
                        <?php if ($block->escapeHtml($reply->getAdminId())) : ?>
                             <?= $block->escapeHtml($block->repliedBy($reply->getAdminId())) ?>
                        <?php else : ?>
                            <p>Me</p>
                        <?php endif; ?> 
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Comment')) ?>" class="col comment"><?= $block->escapeHtml($reply->getComment()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a class="action reply" href="<?= $block->escapeUrl($block->getUrl('support/reply/newreply', ['id' => $reply->getSupportId()])) ?>">
                                <span><?= $block->escapeHtml(__('Reply')) ?></span>
                            </a>
                            <?php if (!$block->escapeHtml($reply->getAdminId())) : ?>
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('support/reply/editreply', ['id' => $reply->getId()])) ?>">
                                <span><?= $block->escapeHtml(__('Edit')) ?></span>
                            </a>
                            <a class="action delete" href="<?= $block->escapeUrl($block->getUrl('support/reply/delete', ['id' => $reply->getId()])) ?>">
                                <span><?= $block->escapeHtml(__('Delete')) ?></span>
                            </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getChildHtml('pager')) : ?>
        <div class="support-ticket-toolbar toolbar bottom"><?= $block->getChildHtml('pager') ?></div>
        <?php endif; ?>    
    </div>
    <div class="secondary">
    <a class="action back" href="<?= $block->getBackUrl() ?>">
        <span><?= $block->escapeHtml(__('Go Back')) ?></span>
    </a>
    </div>
</div>